/* ════════════════════════════════════════════
   data.js — Game data constants
   Loaded before script.js
════════════════════════════════════════════ */

/* ── Wild Magic Surge Table (D&D 5e, 50 effects mapped to d100) ── */
const WILD_MAGIC = [
  "Roll on this table at the start of each of your turns for the next minute, ignoring this result on subsequent rolls.",
  "For the next minute, you can see any invisible creature if you have line of sight to it.",
  "A modron chosen and controlled by the DM appears in an unoccupied space within 5 feet of you, then disappears 1 minute later.",
  "You cast fireball as a 3rd-level spell centered on yourself.",
  "You cast magic missile as a 5th-level spell.",
  "Roll a d10. Your height changes by a number of inches equal to the roll. Odd = shrink, even = grow.",
  "You cast confusion centered on yourself.",
  "For the next minute, you regain 5 hit points at the start of each of your turns.",
  "You grow a long beard made of feathers that remains until you sneeze, at which point the feathers explode from your face.",
  "You cast grease centered on yourself.",
  "Creatures have disadvantage on saving throws against the next spell you cast in the next minute that involves a saving throw.",
  "Your skin turns a vibrant shade of blue. A remove curse spell can end this effect.",
  "An eye appears on your forehead for the next minute, granting you advantage on Wisdom (Perception) checks that rely on sight.",
  "For the next minute, all your spells with a casting time of 1 action have a casting time of 1 bonus action instead.",
  "You teleport up to 60 feet to an unoccupied space of your choice that you can see.",
  "You are transported to the Astral Plane until the end of your next turn, after which you return to the space you previously occupied.",
  "Maximize the damage of the next damaging spell you cast within the next minute.",
  "Roll a d10. Your age changes by a number of years equal to the roll. Odd = younger (min 1 year old), even = older.",
  "1d6 flumphs controlled by the DM appear in unoccupied spaces within 60 feet and are frightened of you. They vanish after 1 minute.",
  "You regain 2d10 hit points.",
  "You turn into a potted plant until the start of your next turn. While a plant, you are incapacitated and have vulnerability to all damage.",
  "For the next minute, you can teleport up to 20 feet as a bonus action on each of your turns.",
  "You cast levitate on yourself.",
  "A unicorn controlled by the DM appears in a space within 5 feet of you, then disappears 1 minute later.",
  "You can't speak for the next minute. Whenever you try, pink bubbles float out of your mouth.",
  "A spectral shield hovers near you for the next minute, granting you +2 AC and immunity to magic missile.",
  "You are immune to being intoxicated by alcohol for the next 5d6 days.",
  "Your hair falls out but grows back within 24 hours.",
  "For the next minute, any flammable object you touch that isn't worn or carried by someone else bursts into flame.",
  "You regain your lowest-level expended spell slot.",
  "For the next minute, you must shout when you speak.",
  "You cast fog cloud centered on yourself.",
  "Up to three creatures you choose within 30 feet of you take 4d10 lightning damage.",
  "You are frightened by the nearest creature until the end of your next turn.",
  "Each creature within 30 feet of you becomes invisible for the next minute. Invisibility ends on a creature when it attacks or casts a spell.",
  "You gain resistance to all damage for the next minute.",
  "A random creature within 60 feet of you becomes poisoned for 1d4 hours.",
  "You glow with bright light in a 30-foot radius for the next minute. Any creature ending its turn within 5 feet of you is blinded until the end of its next turn.",
  "You cast polymorph on yourself. If you fail the saving throw, you turn into a sheep for the spell's duration.",
  "Illusory butterflies and flower petals flutter in the air within 10 feet of you for the next minute.",
  "You can take one additional action immediately.",
  "Each creature within 30 feet of you takes 1d10 necrotic damage. You regain hit points equal to the sum of the necrotic damage dealt.",
  "You cast mirror image.",
  "You cast fly on a random creature within 60 feet of you.",
  "You become invisible until the start of your next turn or until you attack or cast a spell.",
  "If you die within the next minute, you immediately come back to life as if by the reincarnate spell.",
  "Your size increases by one size category for the next minute.",
  "You and all creatures within 30 feet of you gain vulnerability to piercing damage for the next minute.",
  "You are surrounded by faint, ethereal music for the next minute.",
  "You regain all expended sorcery points.",
];

function randFrom(arr) { return arr[Math.floor(Math.random() * arr.length)]; }

/* ── Scene Generator ── */
const SCENE_SETTINGS = [
  'A sunken crypt half-flooded with black water',
  'A merchant\'s wagon on a lonely mountain pass, one wheel broken',
  'The back room of a tavern where the barkeep asks no questions',
  'A ruined temple reclaimed by jungle vines',
  'An arcane library where the books rearrange themselves at night',
  'A crowded city market beneath a sky turning the wrong color',
  'A frozen lake with something large moving beneath the ice',
  'The throne room of an abandoned castle, torches still burning',
  'A smuggler\'s dock at low tide, the boats all gone',
  'An ancient battlefield where crows won\'t land',
  'A carnival tent lit by colored lanterns, crowd unusually quiet',
  'A hedge maze in a noble\'s estate, after midnight',
  'A crossroads with four conflicting signposts',
  'A forge where the fire burns blue and cold',
  'A lighthouse at the cliff\'s edge, its light extinguished',
  'An underground fighting pit, emptied between bouts',
  'A celestial observatory with a cracked, blackened lens',
  'A sinking ship three miles from the nearest shore',
  'A village square where everyone has gathered in complete silence',
  'A garden where flowers bloom only in darkness',
  'A mirror maze in which the reflections are always one step behind',
  'A prison cell — whether occupied or recently vacated',
  'The peak of a tower during a lightning storm',
  'A desert oasis that appears on no map',
  'A flooded street in a city that should be dry',
  'A cathedral whose stained glass depicts events that have not happened yet',
  'A vast salt flat at dusk, the only landmark a single unmarked pillar',
  'A river barge drifting with no one at the helm',
  'An apothecary whose every jar is labeled in a dead language',
  'A bandit camp abandoned mid-meal, fires still warm',
  'An underground dock where torchlight doubles in black water',
  'A noble\'s portrait gallery where every subject faces away from the viewer',
  'A collapsed bridge over a ravine, one rope still intact',
  'A roadside shrine surrounded by offerings no ordinary traveler would leave',
  'An island the locals swear was not there last week',
  'A wizard\'s tower whose staircase ascends into cloud and does not return',
  'A battlefield field hospital, cots still made, long since abandoned',
  'A vineyard at harvest where the workers have vanished mid-row',
  'A deep forest clearing perfectly circular, nothing growing inside it',
  'A palace kitchen at midnight, ovens still hot, no one working',
  'A harbor city under quarantine with one gate still inexplicably open',
  'A cliff-face monastery accessible only by rope ladder',
  'A burning farmstead on the edge of a silent wood',
  'An ancient stone circle where the wind always blows inward',
  'A flooded mine, the water level rising slowly from below',
  'A crowded refugee camp on the border of two hostile kingdoms',
  'A tavern built inside the ribcage of a colossal fallen creature',
  'A grand theater mid-performance with no audience in the seats',
  'A vault door standing open in the middle of an empty field, no vault behind it',
  'A mountain shrine where all the votive candles have been deliberately snuffed',
];

const SCENE_ATMOSPHERES = [
  'Oppressive silence — even footsteps seem swallowed',
  'Everyone present is watching the party without looking at them',
  'The air smells of rain, iron, and something burning',
  'A sense of being watched from just out of sight',
  'Frantic energy — something terrible just happened here',
  'Uneasy calm, the kind that comes just before violence',
  'Jovial noise masking genuine desperation underneath',
  'A low hum no one can quite locate the source of',
  'Cold that has nothing to do with the temperature',
  'Everything is slightly wrong — angles, faces, echoes',
  'The light is dimming faster than it should',
  'Distant music that grows louder whenever you stop moving',
  'Two factions in the same space, barely keeping a truce',
  'Overwhelming sorrow, still fresh',
  'Charged anticipation the locals seem to share in secret',
  'The smell of magic recently and violently spent',
  'An argument heard clearly but the speakers are nowhere to be seen',
  'One figure stands absolutely still in the center of it all',
  'Time feels elastic — moments stretch, then snap forward',
  'Everyone present is pretending not to be afraid',
  'A language is being spoken that none of the party recognize',
  'The animals have all gone silent',
  'Something is being celebrated — no one will say what',
  'A thick fog that stays chest-height and perfectly still',
  'The feeling of being underground even under open sky',
  'The candles here all burn at exactly the same height',
  'Everyone present moves with the ease of a rehearsed routine',
  'A weight in the chest — the feeling of arriving somewhere too late',
  'Every surface has been recently and thoroughly cleaned',
  'The shadow of something very large passes overhead without slowing',
  'Relief, fragile and short-lived, and clearly misplaced',
  'The distinct sense that someone left the room just before you entered',
  'Laughter that stops the moment it is noticed',
  'Dust hangs motionless in the air as though just disturbed',
  'An unusual number of locks, latches, and barred interior doors',
  'The light source never seems to be where you look for it',
  'Nothing is broken, but everything looks braced to be',
  'A low rhythmic sound from below that might be breathing',
  'The locals answer only what they are directly asked, nothing more',
  'A faint sweetness in the air that nobody mentions',
  'The feeling of moving through someone else\'s unfinished dream',
  'Children are absent from this place and no one has remarked on it',
  'Every window and mirror has been deliberately covered',
  'Someone here is trying very hard to appear calm',
  'The temperature drops sharply the moment you cross the threshold',
  'An odd pride among those present — the bearing of survivors',
  'The echoes in this place come back slightly wrong',
  'An official is present who should have no jurisdiction here whatsoever',
  'Everyone here wears the look of someone waiting for permission to leave',
  'The smoke from the fire drifts sideways, against the wind',
];

const SCENE_HOOKS = [
  'A stranger presses a sealed letter into your hand, then walks away without looking back',
  'The person you came to meet is already dead',
  'Someone here recognizes one of you — and it is not a warm reunion',
  'A child has been following the party at a careful distance',
  'The only visible exit is now guarded',
  'A price has been placed on someone\'s head. You are not certain whose',
  'Something you need is in plain sight — so are the people who want it gone',
  'An explosion, a scream, or a crash interrupts everything at once',
  'A deal is being struck nearby that will go very badly for someone in this room',
  'You are being set up. The question is by whom, and for what',
  'The body has not been moved yet',
  'An item belonging to one of you is in someone else\'s possession',
  'A door that was locked is open. A door that was open is now sealed',
  'Something is wrong with the sky',
  'The locals are evacuating quietly and will not say why',
  'You have perhaps five minutes before someone important arrives',
  'A name you all know comes up in a conversation you were not meant to hear',
  'There are more people here than there should be — and fewer than there were a moment ago',
  'Something was taken from this place recently. You can see exactly where it stood',
  'A signal is given. Everyone in the room except the party reacts to it',
  'The layout of this place does not match what you were told',
  'A familiar face appears somewhere it absolutely should not be',
  'One of the locals is very visibly lying about something trivially small',
  'The job was already done by someone else before you arrived',
  'Night falls two hours early',
  'A map is pinned to the wall with a blade through it',
  'Someone offers you work that pays suspiciously well for suspiciously little detail',
  'A face in the crowd mouths a single word at you, then is gone',
  'The thing you came here to find is already in someone else\'s possession',
  'A prisoner is being transported through. No one will confirm the destination',
  'Three separate people give you three different names for this place',
  'A dying stranger presses something small and cold into your hand',
  'Someone has been following the party since before you arrived here',
  'A fire starts somewhere important at the worst possible moment',
  'Your arranged contact sends a proxy instead — a child, alone',
  'Two other parties are after the same thing, neither aware of the other',
  'Something you were told would be here has been moved very recently',
  'A symbol none of you recognize keeps appearing in unrelated places',
  'Someone in this room owes a debt to someone else in this room',
  'There is blood on the floor, fresh, and no one mentions it',
  'You are offered sanctuary — the terms are never fully stated',
  'An ally sends word: abandon the mission, leave now, do not explain',
  'The creature you were hired to kill is already seated at the table',
  'A guard post stands unmanned. It was occupied less than an hour ago',
  'One of you is certain you have been here before. None of you have',
  'A trapdoor in the floor shows signs of very recent use from below',
  'The reward for this task turns out to already be in your possession',
  'An identical version of this scene is described in a book one of you read years ago',
  'The job was done before you arrived. Someone wants to discuss payment anyway',
  'A clock marks the wrong hour. Everyone in the room ignores it',
];

/* ── NPC Generator Data ── */
const NPC_NAMES_HUMAN    = ['Aldric','Mira','Dane','Seraphine','Tobias','Lena','Garret','Vesna','Corvin','Aelys'];
const NPC_NAMES_ELF      = ['Erevan','Sylara','Caladwen','Thalion','Ithilwen','Aerindel','Faeron','Nimloth'];
const NPC_NAMES_DWARF    = ['Dugal','Thora','Bofri','Helga','Gorrim','Brynja','Aldun','Sigrid'];
const NPC_NAMES_HALFLING = ['Milo','Rosie','Pip','Cora','Toblen','Nibs','Fenwick','Lila'];
const NPC_NAMES_TIEFLING = ['Zariel','Mordecai','Sekhara','Vex','Riven','Calyx','Irae','Pyrax'];
const NPC_NAMES_OTHER    = ['Krex','Shavi','Dorn','Tusk','Izara','Vorn','Grix','Nalara'];

const NPC_RACE_POOL = [
  { race: 'Human',    names: NPC_NAMES_HUMAN    },
  { race: 'Elf',      names: NPC_NAMES_ELF      },
  { race: 'Dwarf',    names: NPC_NAMES_DWARF    },
  { race: 'Halfling', names: NPC_NAMES_HALFLING  },
  { race: 'Tiefling', names: NPC_NAMES_TIEFLING  },
  { race: 'Half-Orc', names: NPC_NAMES_OTHER    },
  { race: 'Gnome',    names: NPC_NAMES_OTHER    },
];

const NPC_CLASSES = [
  'Fighter','Wizard','Rogue','Cleric','Ranger','Paladin',
  'Bard','Druid','Warlock','Monk','Barbarian','Sorcerer',
  'Merchant','Guard','Innkeeper','Scholar','Farmer','Sailor',
  'Blacksmith','Herbalist','Assassin','Spy','Cultist','Noble',
];

const NPC_IDEALS = [
  'Power — the strong rule, the weak serve',
  'Knowledge — understanding is its own reward',
  'Freedom — no one should be caged by another\'s will',
  'Community — we survive together or not at all',
  'Redemption — every soul deserves a second chance',
  'Honor — my word is iron',
  'Ambition — greatness is built, not given',
  'Justice — wrongs must be made right, whatever the cost',
  'Survival — tomorrow matters more than today\'s principles',
  'Beauty — the world deserves art, even in darkness',
];

const NPC_BONDS = [
  'Searching for a sibling who vanished years ago',
  'Owes a life-debt to a traveling stranger',
  'Protecting a secret that would destroy their family\'s name',
  'In love with someone they can never approach',
  'Trying to buy back land stolen by a corrupt lord',
  'Keeping a dying promise to their mentor',
  'Guarding a relic they don\'t fully understand',
  'Seeking the person who betrayed their guild',
  'Raising a child alone after the war took everything',
  'Loyal to a cause even as it crumbles around them',
];

const NPC_FLAWS = [
  'Gambles away money they cannot afford to lose',
  'Quick to take offense at perceived slights',
  'Lies reflexively, even when truth would serve better',
  'Cowardly when it truly matters',
  'Cannot resist a secret — will pry at any cost',
  'Holds grudges far longer than is healthy',
  'Drinks to silence a memory',
  'Dismissive of anyone not of their class',
  'Overlooks red flags when offered flattery',
  'Paralyzed by indecision under pressure',
];

const NPC_LOOKS = [
  'A deep scar runs across the jaw',
  'Eyes of two different colors',
  'Missing the tip of the left ear',
  'Ink-stained fingers that never seem clean',
  'A nervous tic — blinks rapidly when lying',
  'Elaborate tattoos visible at the collar and wrist',
  'Always overdressed for the occasion',
  'Hair prematurely white',
  'Smells faintly of woodsmoke',
  'Wears a ring that clearly does not fit',
];

/* ── D4 Fate Faces ── */
const D4_FACES = [
  {
    name: 'Navnlos', value: 1, logChar: '☠',
    phrase: 'Navnlos is judging your actions',
    icon: '&#9760;',
    color: '#d8b4fe', glow: 'rgba(216,180,254,0.7)', bg: 'rgba(168,85,247,0.12)', border: 'rgba(192,132,252,0.55)',
  },
  {
    name: 'Bolverk', value: 2, logChar: '▲',
    phrase: 'Bolverk has an eye on you',
    icon: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 3L3 10h4l-3 9 8-4 8 4-3-9h4z"/></svg>',
    color: '#4ade80', glow: 'rgba(74,222,128,0.7)',  bg: 'rgba(34,197,94,0.12)',  border: 'rgba(74,222,128,0.55)',
  },
  {
    name: 'Pandora', value: 3, logChar: '♥',
    phrase: 'Pandora likes you',
    icon: '&#9829;',
    color: '#f472b6', glow: 'rgba(244,114,182,0.7)', bg: 'rgba(236,72,153,0.12)', border: 'rgba(244,114,182,0.55)',
  },
  {
    name: 'Eevona', value: 4, logChar: '✦',
    phrase: 'Eevona is writing your story',
    icon: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M2 4h9v16H2zM13 4h9v16h-9zM11 3h2v18h-2z"/></svg>',
    color: '#a855f7', glow: 'rgba(168,85,247,0.7)',  bg: 'rgba(109,40,217,0.18)', border: 'rgba(124,58,237,0.65)',
  },
];

/* ── Major Arcana Tarot ── */
const TAROT = [
  { num:  0, name: 'The Fool',         symbol: '∅', color: '#94a3b8', upright: 'New beginnings, leap of faith',       reversed: 'Recklessness, poor judgment'         },
  { num:  1, name: 'The Magician',     symbol: '⌁', color: '#f59e0b', upright: 'Willpower, skill, manifestation',    reversed: 'Manipulation, untapped talent'       },
  { num:  2, name: 'High Priestess',   symbol: '☽', color: '#818cf8', upright: 'Intuition, mystery, inner wisdom',   reversed: 'Secrets withheld, disconnection'     },
  { num:  3, name: 'The Empress',      symbol: '✦', color: '#4ade80', upright: 'Abundance, fertility, nature',       reversed: 'Dependence, creative block'          },
  { num:  4, name: 'The Emperor',      symbol: '⊕', color: '#ef4444', upright: 'Authority, structure, stability',    reversed: 'Rigidity, domination, inflexibility' },
  { num:  5, name: 'The Hierophant',   symbol: '✠', color: '#a78bfa', upright: 'Tradition, institutions, ritual',    reversed: 'Rebellion, unconventional path'      },
  { num:  6, name: 'The Lovers',       symbol: '♥', color: '#f472b6', upright: 'Union, harmony, aligned values',     reversed: 'Disharmony, imbalance, separation'   },
  { num:  7, name: 'The Chariot',      symbol: '⊗', color: '#3b82f6', upright: 'Control, victory, determination',    reversed: 'Aggression, lack of direction'       },
  { num:  8, name: 'Strength',         symbol: '∞', color: '#f97316', upright: 'Courage, patience, compassion',      reversed: 'Self-doubt, weakness, inner fear'    },
  { num:  9, name: 'The Hermit',       symbol: '⋆', color: '#9ca3af', upright: 'Solitude, inner guidance, truth',    reversed: 'Isolation, loneliness, exile'        },
  { num: 10, name: 'Wheel of Fortune', symbol: '⊙', color: '#fbbf24', upright: 'Luck, fate, turning point',          reversed: 'Bad luck, resistance, stagnation'    },
  { num: 11, name: 'Justice',          symbol: '≡', color: '#60a5fa', upright: 'Fairness, truth, cause and effect',  reversed: 'Injustice, dishonesty, bias'         },
  { num: 12, name: 'The Hanged Man',   symbol: '⊜', color: '#34d399', upright: 'Surrender, new perspective, pause',  reversed: 'Indecision, delay, stalling'         },
  { num: 13, name: 'Death',            symbol: '☠', color: '#8b9196', upright: 'Endings, transformation, release',   reversed: 'Resistance, stagnation, decay'       },
  { num: 14, name: 'Temperance',       symbol: '≈', color: '#22d3ee', upright: 'Balance, patience, moderation',      reversed: 'Imbalance, excess, misalignment'     },
  { num: 15, name: 'The Devil',        symbol: '⊥', color: '#dc2626', upright: 'Shadow self, addiction, bondage',    reversed: 'Release, reclaiming power, freedom'  },
  { num: 16, name: 'The Tower',        symbol: '⌇', color: '#fb923c', upright: 'Sudden change, chaos, revelation',   reversed: 'Avoiding disaster, delay, fear'      },
  { num: 17, name: 'The Star',         symbol: '★', color: '#93c5fd', upright: 'Hope, renewal, serenity, faith',     reversed: 'Despair, lack of faith, insecurity'  },
  { num: 18, name: 'The Moon',         symbol: '◑', color: '#c4b5fd', upright: 'Illusion, fear, the unconscious',    reversed: 'Release of fear, repressed emotion'  },
  { num: 19, name: 'The Sun',          symbol: '☀', color: '#fcd34d', upright: 'Joy, success, vitality, clarity',    reversed: 'Ego, overconfidence, temporary gloom'},
  { num: 20, name: 'Judgement',        symbol: '⊚', color: '#a78bfa', upright: 'Renewal, absolution, inner calling', reversed: 'Self-doubt, refusal to change'       },
  { num: 21, name: 'The World',        symbol: '◯', color: '#86efac', upright: 'Completion, wholeness, travel',      reversed: 'Incompletion, lack of closure'       },
];

/* ── Deck of Many Things (22 cards, D&D 5e) ── */
const DOMT = [
  { num:  1, name: 'The Vizier',  symbol: '⌂', color: '#22d3ee',
    upright: 'Within one year you may ask one question and receive a true answer. The wisdom to use it wisely is also granted.' },
  { num:  2, name: 'The Sun',     symbol: '☀', color: '#fcd34d',
    upright: 'You gain 50,000 XP, and a wondrous item (DM\'s choice) appears in your hands.' },
  { num:  3, name: 'The Moon',    symbol: '☾', color: '#c4b5fd',
    upright: 'You are granted 1d3 wishes (as the wish spell).' },
  { num:  4, name: 'The Star',    symbol: '★', color: '#93c5fd',
    upright: 'Increase one ability score of your choice by 2. The score can exceed its normal maximum of 20.' },
  { num:  5, name: 'The Throne',  symbol: '♛', color: '#f59e0b',
    upright: 'You gain proficiency in Persuasion, and a small keep appears in a wilderness location of your choice.' },
  { num:  6, name: 'Key',         symbol: '⚿', color: '#86efac',
    upright: 'A rare or rarer magic weapon with which you are proficient appears in your hands.' },
  { num:  7, name: 'Knight',      symbol: '⚔', color: '#60a5fa',
    upright: 'You gain the service of a 4th-level fighter who appears in a space of your choosing within 30 feet.' },
  { num:  8, name: 'The Gem',     symbol: '◈', color: '#38bdf8',
    upright: '25 pieces of jewelry worth 2,000 gp each, or 50 gems worth 1,000 gp each, appear at your feet.' },
  { num:  9, name: 'The Fates',   symbol: '✂', color: '#34d399',
    upright: 'Reality\'s fabric unravels. You may avoid or erase one event as if it never happened — even rewriting history.' },
  { num: 10, name: 'Jester',      symbol: '⟡', color: '#fbbf24',
    upright: 'Gain 10,000 XP — or choose to draw two additional cards beyond your declared number.' },
  { num: 11, name: 'Comet',       symbol: '☄', color: '#fde68a',
    upright: 'If you single-handedly defeat the next hostile creature you encounter, you gain enough XP to reach the next level.' },
  { num: 12, name: 'Balance',     symbol: '⚖', color: '#818cf8',
    upright: 'Your alignment changes. Lawful becomes chaotic, good becomes evil, and vice versa — as the DM adjudicates.' },
  { num: 13, name: 'The Rogue',   symbol: '◗', color: '#f87171',
    upright: 'An NPC of the DM\'s choice becomes secretly hostile, plotting your ruin from the shadows.' },
  { num: 14, name: 'The Euryale', symbol: '⊹', color: '#a78bfa',
    upright: 'You are cursed: a −2 penalty to all saving throws. Only a god or divine intervention can remove it.' },
  { num: 15, name: 'The Flames',  symbol: '⌇', color: '#ef4444',
    upright: 'A powerful devil becomes your enemy, seeking your ruin and corrupting those close to you.' },
  { num: 16, name: 'The Skull',   symbol: '☠', color: '#6b7280',
    upright: 'An avatar of death appears. You must fight it alone — no aid permitted. Defeat means your soul departs.' },
  { num: 17, name: 'Idiot',       symbol: '⊖', color: '#9ca3af',
    upright: 'Permanently reduce your Intelligence by 1d4+1 (minimum 1). You may draw one additional card.' },
  { num: 18, name: 'The Fool',    symbol: '◌', color: '#94a3b8',
    upright: 'You lose 10,000 XP, discard the card, and must draw again — whether you want to or not.' },
  { num: 19, name: 'The Ruin',    symbol: '✕', color: '#dc2626',
    upright: 'All nonmagical wealth you carry or own — coin, property, goods — is lost to you forever.' },
  { num: 20, name: 'Talons',      symbol: '∇', color: '#f97316',
    upright: 'Every magic item you wear or carry disintegrates instantly. Artifacts are unaffected.' },
  { num: 21, name: 'The Donjon',  symbol: '⊞', color: '#4b5563',
    upright: 'You vanish and are imprisoned in a demiplane. You draw no more cards. Only a wish can free you.' },
  { num: 22, name: 'The Void',    symbol: '◉', color: '#7c3aed',
    upright: 'Your soul is drawn from your body and imprisoned in an object chosen by the DM. Your body becomes catatonic.' },
];

/* ── Minor Arcana (56 cards) ── */
const TAROT_MINOR = (function () {
  const SUITS = [
    { suit: 'Wands',     color: '#f97316', symbol: 'ψ' },
    { suit: 'Cups',      color: '#38bdf8', symbol: '♆' },
    { suit: 'Swords',    color: '#94a3b8', symbol: '⚔' },
    { suit: 'Pentacles', color: '#4ade80', symbol: '⊕' },
  ];
  const RANKS = [
    { label: 'Ac', name: 'Ace'    },
    { label: '02', name: 'Two'    },
    { label: '03', name: 'Three'  },
    { label: '04', name: 'Four'   },
    { label: '05', name: 'Five'   },
    { label: '06', name: 'Six'    },
    { label: '07', name: 'Seven'  },
    { label: '08', name: 'Eight'  },
    { label: '09', name: 'Nine'   },
    { label: '10', name: 'Ten'    },
    { label: 'Pg', name: 'Page'   },
    { label: 'Kn', name: 'Knight' },
    { label: 'Qu', name: 'Queen'  },
    { label: 'Kg', name: 'King'   },
  ];
  const M = {
    Wands: {
      Ace:    ['Creation, inspiration',         'Delays, lack of direction'          ],
      Two:    ['Planning, discovery',            'Fear of unknown, stagnation'        ],
      Three:  ['Expansion, foresight',           'Playing it safe, missed opportunity'],
      Four:   ['Celebration, harmony',           'Personal conflict, tension'         ],
      Five:   ['Competition, conflict',          'Avoiding confrontation'             ],
      Six:    ['Victory, recognition',           'Egotism, fall from grace'           ],
      Seven:  ['Perseverance, challenge',        'Giving up, overwhelmed'             ],
      Eight:  ['Speed, swift action',            'Delays, frustration'                ],
      Nine:   ['Resilience, persistence',        'Struggle, exhaustion'               ],
      Ten:    ['Burden, responsibility',         'Inability to delegate'              ],
      Page:   ['Enthusiasm, exploration',        'Setbacks, immaturity'               ],
      Knight: ['Adventure, bold action',         'Recklessness, scattered energy'     ],
      Queen:  ['Confidence, determination',      'Jealousy, selfishness'              ],
      King:   ['Vision, leadership',             'Impulsiveness, ruthlessness'        ],
    },
    Cups: {
      Ace:    ['New feelings, intuition',        'Blocked creativity, emptiness'      ],
      Two:    ['Partnership, attraction',        'Imbalance, break-up'                ],
      Three:  ['Friendship, community',          'Independence, overindulgence'       ],
      Four:   ['Contemplation, meditation',      'Missed opportunity, boredom'        ],
      Five:   ['Loss, regret',                   'Acceptance, moving on'              ],
      Six:    ['Nostalgia, revisiting the past', 'Living in the past, naivety'        ],
      Seven:  ['Fantasy, illusion',              'Alignment, reality check'           ],
      Eight:  ['Withdrawal, disillusionment',    'Avoidance, fear of change'          ],
      Nine:   ['Satisfaction, fulfilment',       'Dissatisfaction, complacency'       ],
      Ten:    ['Happiness, family harmony',      'Broken bonds, discord'              ],
      Page:   ['Creative curiosity, messages',   'Emotional immaturity, moodiness'    ],
      Knight: ['Romance, following the heart',   'Moodiness, disappointment'          ],
      Queen:  ['Compassion, intuitive calm',     'Insecurity, dependence'             ],
      King:   ['Emotional wisdom, diplomacy',    'Manipulation, emotional coldness'   ],
    },
    Swords: {
      Ace:    ['Clarity, breakthrough',          'Confusion, chaos'                   ],
      Two:    ['Stalemate, difficult choice',    'Information overload, confusion'    ],
      Three:  ['Heartbreak, sorrow',             'Recovery, forgiveness'              ],
      Four:   ['Rest, recuperation',             'Restlessness, burnout'              ],
      Five:   ['Conflict, defeat',               'Reconciliation, making amends'      ],
      Six:    ['Transition, moving on',          'Stuck, unable to move forward'      ],
      Seven:  ['Deception, strategy',            'Truth revealed, coming clean'       ],
      Eight:  ['Restriction, powerlessness',     'Freedom, taking back control'       ],
      Nine:   ['Anxiety, despair',               'Hope, reaching out for help'        ],
      Ten:    ['Betrayal, painful ending',       'Recovery, rising again'             ],
      Page:   ['Mental agility, new ideas',      'Scattering thoughts, deception'     ],
      Knight: ['Ambition, swift action',         'Aggression, impulsiveness'          ],
      Queen:  ['Perceptive, independent mind',   'Cold-hearted, overly critical'      ],
      King:   ['Intellectual authority, clarity','Manipulation, power misused'        ],
    },
    Pentacles: {
      Ace:    ['Opportunity, prosperity',        'Missed chance, poor planning'       ],
      Two:    ['Balance, juggling priorities',   'Disorganisation, overwhelm'         ],
      Three:  ['Teamwork, craftsmanship',        'Disharmony, poor work ethic'        ],
      Four:   ['Security, stability',            'Greed, hoarding, stagnation'        ],
      Five:   ['Hardship, isolation',            'Recovery, charitable help'          ],
      Six:    ['Generosity, giving',             'Debt, strings attached'             ],
      Seven:  ['Investment, long-term vision',   'Impatience, lack of reward'         ],
      Eight:  ['Diligence, skill-building',      'Perfectionism, self-critique'       ],
      Nine:   ['Abundance, self-reliance',       'Financial failure, over-investment' ],
      Ten:    ['Wealth, legacy, family',         'Financial loss, loneliness'         ],
      Page:   ['Opportunity, study',             'Procrastination, lack of focus'     ],
      Knight: ['Efficiency, hard work',          'Laziness, perfectionism'            ],
      Queen:  ['Nurturing, practical care',      'Neglect, financial insecurity'      ],
      King:   ['Security, discipline, provider', 'Inflexibility, greed'              ],
    },
  };
  return SUITS.flatMap(s =>
    RANKS.map(r => ({
      label:    r.label,
      name:     `${r.name} of ${s.suit}`,
      symbol:   s.symbol,
      color:    s.color,
      suit:     s.suit,
      upright:  M[s.suit][r.name][0],
      reversed: M[s.suit][r.name][1],
    }))
  );
})();

/* ── NPC Generator ── */
const NPC_RACES = ['human', 'elf', 'dwarf', 'halfling', 'tiefling', 'orc', 'gnome'];

const NPC_NAMES = {
  human:    {
    m:    ['Aldric','Bram','Cade','Davan','Eran','Finn','Gareth','Hollis','Ivan','Joren','Kade','Leoric','Nolan','Owen','Raef','Sander','Tomas','Ulric','Wren'],
    f:    ['Alara','Bryn','Calla','Devra','Elara','Fern','Gwen','Hessa','Ilara','Jana','Kira','Lyra','Mira','Nara','Opal','Petra','Reva','Sara','Tara','Una'],
    last: ['Ashwood','Blackthorn','Coldwater','Dawnhaven','Fairbrook','Fenwhistle','Greymoor','Holloway','Ironforge','Kestrel','Lightstone','Mossbridge','Nightfall','Oakhart','Pendleton','Proudmoor','Riverrun','Stormwall','Thorngate','Underwood','Whitfield'],
  },
  elf:      {
    m:    ['Aelindra','Caladrel','Elathon','Faolin','Galanodel','Laucian','Quarion','Riardon','Soveliss','Thamior','Varis','Zilvara'],
    f:    ['Adrie','Birel','Caelynn','Dara','Enna','Faral','Irann','Keyleth','Leshanna','Mialee','Quelenna','Thia','Valanthe'],
    last: ['Brightleaf','Dawnwhisper','Embersong','Evenfall','Glimmerbrook','Goldenmane','Leafwhisper','Moonshadow','Nightbloom','Shadewarden','Silverwind','Starweave','Sunbrook','Willowmere','Windwhisper'],
  },
  dwarf:    {
    m:    ['Adrik','Baern','Bromur','Dolgrin','Eberk','Fargrim','Harbek','Kildrak','Morgran','Orsik','Rurik','Taklinn','Thorin','Tordek','Ulfgar'],
    f:    ['Amber','Artin','Audhild','Bardryn','Dagnal','Diesa','Eldeth','Falkrunn','Gunnloda','Helja','Kathra','Mardred','Riswynn','Torbera','Vistra'],
    last: ['Axebreaker','Bronzepick','Copperforge','Deepdelve','Deeprock','Flintstone','Goldpick','Hammerfall','Ironmantle','Ironfist','Orebrow','Rockseam','Steelmantle','Stonehall','Thunderbeard'],
  },
  halfling: {
    m:    ['Alton','Ander','Cade','Corrin','Errich','Finnan','Garret','Lindal','Merric','Milo','Osborn','Perrin','Reed','Roscoe','Wellby'],
    f:    ['Andry','Bree','Callie','Cora','Euphemia','Jillian','Kithri','Lavinia','Lidda','Merla','Nedda','Portia','Seraphina','Trym','Wella'],
    last: ['Brightwater','Brambletoes','Goodbarrel','Greenbottle','Highhill','Leagallow','Longtunnel','Merrymoor','Tealeaf','Tosscobble','Underfoot','Wobblewick'],
  },
  tiefling: {
    m:    ['Akmenos','Amnon','Barakas','Damakos','Ekemon','Iados','Kairon','Leucis','Melech','Morthos','Pelaios','Skamos','Therai'],
    f:    ['Akta','Anakis','Bryseis','Criella','Damaia','Ea','Kallista','Lerissa','Makaria','Nemeia','Orianna','Phelaia','Rieta'],
    last: ['Ashblood','Ashenkind','Darkflame','Emberveil','Embersoul','Hellscar','Malasoul','Shadowborn','Shadowweave','Sinmark','Soulbane','Voidmark'],
  },
  orc:      {
    m:    ['Drog','Grom','Gruk','Karg','Kor','Mog','Reth','Thag','Urk','Varg','Wark','Zug'],
    f:    ['Gasha','Karga','Morga','Nura','Okra','Urga','Varka','Zarsha'],
    last: ['Bloodtusk','Bonecrusher','Clanhammer','Crushrock','Eyegouger','Ironhide','Ironjaw','Marrowcrunch','Neckgrip','Scarface','Skullbreak','Stonefist','Wargrunt'],
  },
  gnome:    {
    m:    ['Alston','Alvyn','Boddynock','Brocc','Burgell','Dimble','Fonkin','Gimble','Glim','Kellen','Namfoodle','Orryn','Roondar','Seebo','Zook'],
    f:    ['Bimpnottin','Breena','Caramip','Carlin','Donella','Ella','Ellywick','Lilli','Lorilla','Nissa','Nyx','Orla','Roywyn','Tana','Zanna'],
    last: ['Beren','Bumblefig','Clatterwick','Clumble','Crankspring','Daergel','Folkor','Garrick','Glimmerwick','Nackle','Ningel','Raulnor','Scheppen','Tinkertop','Timbers'],
  },
};

const NPC_OCCUPATIONS = [
  'blacksmith','innkeeper','merchant','town guard','scholar','healer','herbalist',
  'cartographer','scribe','fletcher','apothecary','stablehand','fence','courier',
  'fortune teller','butcher','moneylender','mason','shipwright','fisherman',
  'traveling bard','gravedigger','leatherworker','glassblower','rat catcher',
];

const NPC_TRAITS = [
  'speaks in a whisper no matter the situation',
  'laughs at their own jokes before finishing them',
  'constantly checks over their shoulder',
  'refers to themselves in the third person',
  'uses proverbs that never quite fit the moment',
  'seems to know everyone by name but never explains how',
  'asks deeply personal questions with no apparent awareness this is odd',
  'pauses for exactly three seconds before responding to anything',
  'cannot make eye contact but is otherwise very confident',
  'finishes other people\'s sentences, always incorrectly',
  'hums softly to themselves whenever nervous',
  'has a strong opinion about everything and shares all of them',
  'is unfailingly polite even when clearly furious',
  'references "the old days" in every conversation',
  'wears a single distinctive item they refuse to discuss',
  'refuses all food or drink they haven\'t personally inspected',
  'speaks in elaborate metaphors for the most mundane things',
  'has a habit of going completely still mid-sentence',
  'is visibly delighted by minor inconveniences that befall others',
  'collects objects of one very specific type and becomes upset when asked why',
];

const NPC_SECRETS = [
  'is hiding their true identity from a powerful organization',
  'witnessed something they were never meant to see',
  'owes a large debt to someone they have never met in person',
  'is the last surviving member of a noble house',
  'stole something precious years ago and has never returned it',
  'is being blackmailed and has no intention of paying',
  'knows the location of something very valuable and very cursed',
  'has been lying about their expertise for years — successfully',
  'serves a patron whose true nature they have not fully understood',
  'is scouting this area for someone else entirely',
  'once betrayed a close friend and constructed an elaborate justification for it',
  'carries a message they already read and resealed',
  'is not who they were introduced as',
  'is looking for someone they claim not to know',
  'has a second family in another city who knows nothing of the first',
  'recently survived something they cannot explain and have told no one',
  'is here on specific instructions they are pretending to have forgotten',
  'has a buyer lined up for something they do not yet possess',
];
