/* ════════════════════════════════════════════
   data.js — Game data constants
   Loaded before script.js
════════════════════════════════════════════ */

/* ── Wild Magic Surge Table (D&D 5e, 50 effects mapped to d100) ── */
const WILD_MAGIC = [
  "Roll on this table at the start of each of your turns for the next minute, ignoring this result on subsequent rolls.",
  "For the next minute, you can see any invisible creature if you have line of sight to it.",
  "A modron chosen and controlled by the DM appears in an unoccupied space within 5 feet of you, then disappears 1 minute later.",
  "You cast fireball as a 3rd-level spell centered on yourself.",
  "You cast magic missile as a 5th-level spell.",
  "Roll a d10. Your height changes by a number of inches equal to the roll. Odd = shrink, even = grow.",
  "You cast confusion centered on yourself.",
  "For the next minute, you regain 5 hit points at the start of each of your turns.",
  "You grow a long beard made of feathers that remains until you sneeze, at which point the feathers explode from your face.",
  "You cast grease centered on yourself.",
  "Creatures have disadvantage on saving throws against the next spell you cast in the next minute that involves a saving throw.",
  "Your skin turns a vibrant shade of blue. A remove curse spell can end this effect.",
  "An eye appears on your forehead for the next minute, granting you advantage on Wisdom (Perception) checks that rely on sight.",
  "For the next minute, all your spells with a casting time of 1 action have a casting time of 1 bonus action instead.",
  "You teleport up to 60 feet to an unoccupied space of your choice that you can see.",
  "You are transported to the Astral Plane until the end of your next turn, after which you return to the space you previously occupied.",
  "Maximize the damage of the next damaging spell you cast within the next minute.",
  "Roll a d10. Your age changes by a number of years equal to the roll. Odd = younger (min 1 year old), even = older.",
  "1d6 flumphs controlled by the DM appear in unoccupied spaces within 60 feet and are frightened of you. They vanish after 1 minute.",
  "You regain 2d10 hit points.",
  "You turn into a potted plant until the start of your next turn. While a plant, you are incapacitated and have vulnerability to all damage.",
  "For the next minute, you can teleport up to 20 feet as a bonus action on each of your turns.",
  "You cast levitate on yourself.",
  "A unicorn controlled by the DM appears in a space within 5 feet of you, then disappears 1 minute later.",
  "You can't speak for the next minute. Whenever you try, pink bubbles float out of your mouth.",
  "A spectral shield hovers near you for the next minute, granting you +2 AC and immunity to magic missile.",
  "You are immune to being intoxicated by alcohol for the next 5d6 days.",
  "Your hair falls out but grows back within 24 hours.",
  "For the next minute, any flammable object you touch that isn't worn or carried by someone else bursts into flame.",
  "You regain your lowest-level expended spell slot.",
  "For the next minute, you must shout when you speak.",
  "You cast fog cloud centered on yourself.",
  "Up to three creatures you choose within 30 feet of you take 4d10 lightning damage.",
  "You are frightened by the nearest creature until the end of your next turn.",
  "Each creature within 30 feet of you becomes invisible for the next minute. Invisibility ends on a creature when it attacks or casts a spell.",
  "You gain resistance to all damage for the next minute.",
  "A random creature within 60 feet of you becomes poisoned for 1d4 hours.",
  "You glow with bright light in a 30-foot radius for the next minute. Any creature ending its turn within 5 feet of you is blinded until the end of its next turn.",
  "You cast polymorph on yourself. If you fail the saving throw, you turn into a sheep for the spell's duration.",
  "Illusory butterflies and flower petals flutter in the air within 10 feet of you for the next minute.",
  "You can take one additional action immediately.",
  "Each creature within 30 feet of you takes 1d10 necrotic damage. You regain hit points equal to the sum of the necrotic damage dealt.",
  "You cast mirror image.",
  "You cast fly on a random creature within 60 feet of you.",
  "You become invisible until the start of your next turn or until you attack or cast a spell.",
  "If you die within the next minute, you immediately come back to life as if by the reincarnate spell.",
  "Your size increases by one size category for the next minute.",
  "You and all creatures within 30 feet of you gain vulnerability to piercing damage for the next minute.",
  "You are surrounded by faint, ethereal music for the next minute.",
  "You regain all expended sorcery points.",
];

/* ── Procedural Buff Generator ── */
const BUFFS = [
  // Movement & Senses
  "run at twice your normal speed",
  "see perfectly in complete darkness",
  "gain darkvision out to 120 feet",
  "always know true north",
  "leave no footprints or tracks",
  "never lose your balance",
  "can walk on water and other liquids as though solid ground",
  "are immune to falling damage",
  "can leap to any surface you can see",
  "can fly (but only one inch off the ground)",
  "can phase through solid objects once per minute",
  "can squeeze through any gap larger than your fist",
  // Combat & Offense
  "deal double damage on your first hit each combat",
  "gain a +3 bonus to all attack rolls",
  "all your critical hits deal their maximum possible damage",
  "your critical hit range expands to 18–20",
  "your unarmed strikes count as magical",
  "are blessed: reroll any result of 1 on attacks or saves",
  "can reroll any single die once per round",
  "can take one additional action at the start of combat",
  // Defense & Survival
  "gain resistance to all damage",
  "are immune to fire damage",
  "are immune to all poisons",
  "are immune to extreme cold and heat",
  "are immune to being surprised",
  "are immune to fear and charm effects",
  "are immune to being restrained or grappled",
  "your armor class cannot fall below 18",
  "automatically succeed on death saving throws",
  "regain hit points equal to damage you deal",
  "can heal others with a touch",
  // Magic & Abilities
  "speak and understand all languages",
  "can breathe underwater",
  "never feel hunger or thirst",
  "are aging backwards for 24 hours",
  "are invisible to all undead",
  "can walk through walls once per hour",
  "can turn invisible for 10 seconds at will",
  "can hold two concentration spells simultaneously",
  "your spells require no material components",
  "can cast spells without verbal or somatic components",
  "cast any cantrip without concentration",
  "can identify any spell being cast within 60 feet",
  "can stop time for exactly one second once per round",
  "can charm any creature with a single word",
  "can communicate with the dead by touching them",
  "can summon a spectral steed at will",
  "gain the ability to cast one random 3rd-level spell once",
  // Utility & Knowledge
  "have perfect recall of everything you have witnessed today",
  "have advantage on all Charisma checks",
  "gain proficiency in every skill simultaneously",
  "can smell deception",
  "can mimic any voice you have heard",
  "can read all magical writing instinctively",
  "can read the memories of any object you hold",
  "can see through illusions and disguises instinctively",
  "automatically detect all traps within 30 feet",
  "understand all animal speech",
  "communicate telepathically with willing allies",
  "can predict the weather perfectly for the next week",
  "can see exactly 10 seconds into the future",
  "all your saving throws are made with advantage",
  "are surrounded by an aura that deflects incoming projectiles",
  "grow a second pair of fully functional arms",
];

const CONNECTORS = [
  "but",
  "however,",
  "yet",
  "though",
  "although",
  "but oddly,",
  "except that",
  "and yet somehow,",
  "at the cost that",
  "with the caveat that",
];

const DEBUFFS = [
  // Physical oddities
  "your palms are permanently itchy",
  "you hiccup every ten seconds",
  "your shadow moves independently of you",
  "your teeth glow faintly in the dark",
  "your left eye twitches with great conviction",
  "your nose produces a faint but persistent whistle when you breathe",
  "your voice has shifted exactly one octave higher without warning",
  "your hair has turned a vivid shade of magenta",
  "your hair or beard grows one full inch immediately",
  "your eyes have subtly swapped positions on your face",
  "you are inexplicably and thoroughly damp",
  "you glow faint purple whenever you feel anxious",
  "you weep tiny gemstones instead of tears",
  "your tears have been replaced with something that smells faintly of lavender",
  "your feet are now two degrees colder than the rest of your body",
  "your fingernails have become entirely translucent",
  "you develop a second, smaller chin that has its own opinions",
  // Sensory & perception
  "you smell strongly of cinnamon and dread",
  "you taste copper whenever you blink",
  "you are deeply convinced the number 7 is watching you",
  "the moon appears twice its normal size to you and only you",
  "shadows around you lean consistently in the wrong direction",
  "you can no longer whistle regardless of effort",
  "you have forgotten how to snap your fingers",
  "every coin you touch lands on the same side every time",
  "all mirrors crack when you walk within 5 feet of them",
  // Behavioral & social
  "you sneeze whenever someone nearby tells a lie",
  "you narrate your own actions out loud and cannot stop",
  "you have forgotten everyone's names for one hour",
  "you can only speak in the form of questions",
  "you laugh at entirely inappropriate and solemn moments",
  "you are pathologically incapable of using doors on the first attempt",
  "you occasionally address inanimate objects formally and by name",
  "you are only able to sleep standing upright",
  "you can only communicate in a whisper",
  "you develop a firm belief that you are actually a cloud",
  "you have developed a one-sided rivalry with a specific cloud",
  "you become convinced every meal is slightly too salty",
  // Environmental & magical
  "every door you touch slams loudly",
  "small flowers bloom in every footstep you leave",
  "birds follow you at a distance and judge you silently",
  "your footsteps sound exactly like slow applause",
  "every insect within 30 feet is drawn irresistibly to you",
  "your voice echoes twice after you finish speaking",
  "you cannot stop humming a tune you have never heard before",
  "you keep misplacing objects you were holding moments ago",
  "your sneezes sound like a tiny trumpet fanfare",
  "animals will not make eye contact with you",
  "you leave a faint trail of glitter with each step",
  "small pebbles and stones slowly orbit your head",
  "you can only walk sideways for the next hour",
  "everyone you meet is certain they have met you somewhere before",
  "you emit a quiet but audible hum at all times",
  "all your spellcasting gestures have become interpretive dance",
  "you are magnetically attracted to wet paint",
  "your boots produce a loud and embarrassing squeak",
  "you are trailed by the faint sound of dramatic orchestral music",
  "you develop an intense and unexplained craving for pickled beets",
  "small lightning bolts arc between your fingers when you are bored",
  "furniture slides itself slightly out of your direct path",
  "a persistent question mark made of purple smoke follows you",
  "ink refuses to dry on anything you have personally written",
  "small cacti appear wherever you have been sitting",
  "you leave a faint burnt-toast aroma in any enclosed space",
  "your handwriting has become beautiful but completely illegible",
  "your reflection is always exactly one second delayed",
  "you have permanently lost the ability to wink",
];

function randFrom(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
