/* ════════════════════════════════════════════
   guesswho-data.js — Character roster
   Default source for the Masquerade module.
   Can be swapped at runtime with ⤓ Import
   (that copy lives in localStorage and shadows
   this file until another one is imported).
════════════════════════════════════════════ */

/*  Fields (keys stay in Spanish so rosters exported earlier still import):
      id          unique identifier, never change it once assigned
      jugador     player — who runs the character
      personaje   character — the name shown on the card
      raza        race / base species
      subespecie  subrace / bloodline
      clase       classes and subclasses, verbatim from the spreadsheet
      faccion     guild or pact
      estado      status. Empty = alive and active. Otherwise anything
                  containing dead/muert, missing/desaparec or traitor/traidor
                  is grouped under that category for questions, and shows
                  ☠ / ? / ⚑ on the card. The sheet prints the raw text.
      descripcion 1-2 lines on physical appearance — the extra in-game clue
      lore        backstory, only shown when the sheet is opened
      imagen      relative path to the portrait, e.g. 'guess_who/thumbs/Bolverk.webp'
                  if empty or it fails to load, the initial is drawn instead

    descripcion and lore ship empty: the spreadsheet had no such column.
    Fill them here by hand, or via 💾 Export → edit → ⤓ Import.

    Portraits point at guess_who/thumbs/ (420px webp, ~0.9 MB total). The
    originals stay untouched in guess_who/. To add or replace a photo: drop the
    original in guess_who/, point 'imagen' at it, and run
    `python guesswho_thumbs.py` — it rebuilds stale thumbs and repoints this file.  */

const GUESS_WHO = [

  // ── Aidoneus ──
  {
    id: 'vhaehnae',
    jugador: 'Aidoneus',
    personaje: 'Vhaehnae',
    raza: '',
    subespecie: '',
    clase: 'BladeSinger Wizard | Shadow Monk',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Vhaehnae.webp',
  },
  {
    id: 'titania-venture',
    jugador: 'Aidoneus',
    personaje: 'Titania Venture',
    raza: '',
    subespecie: '',
    clase: 'Scribe Wizard',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Titania Venture.webp',
  },
  {
    id: 'executor-nitokh',
    jugador: 'Aidoneus',
    personaje: 'Executor Nitokh',
    raza: '',
    subespecie: '',
    clase: '',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: [
      'guess_who/thumbs/Nitokh.webp',
      'guess_who/thumbs/Nitokh Unarmored.webp',
    ],
  },

  // ── Göllnyr ──
  {
    id: 'bolverk',
    jugador: 'Göllnyr',
    personaje: 'Bolverk',
    raza: 'Lycan',
    subespecie: '',
    clase: 'Ranger | Fighter',
    faccion: 'Pacto de los Fragmentados',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Bolverk.webp',
  },

  // ── Pandora ──
  {
    id: 'pandora',
    jugador: 'Pandora',
    personaje: 'Pandora',
    raza: 'Wilya',
    subespecie: 'Ramedhel',
    clase: 'Paladin Oath of Vengeance | Battle Master',
    faccion: 'Pacto de los Fragmentados',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Pandora_skin_Eevona.webp',
  },
  {
    id: 'liel',
    jugador: 'Pandora',
    personaje: 'Liel',
    raza: 'Wilya',
    subespecie: 'Ramedhel',
    clase: 'Paladin Oath of the Sword Dancer',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/LAEL.webp',
  },

  // ── Elskan ──
  {
    id: 'dux',
    jugador: 'Elskan',
    personaje: 'Dux',
    raza: 'Suneri',
    subespecie: "Sunerin't",
    clase: 'Arcane Trickster | Way of the Twin Blades Sculptor',
    faccion: 'Ninguno',
    estado: 'Missing',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/dux.webp',
  },
  {
    id: 'elskan',
    jugador: 'Elskan',
    personaje: 'Elskan',
    raza: 'Suneri',
    subespecie: 'Suneri',
    clase: 'Spell Thief | Fighter',
    faccion: 'Pacto de los Fragmentados',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/elskan.webp',
  },

  // ── Paula ──
  {
    id: 'redmor',
    jugador: 'Paula',
    personaje: 'Redmor',
    raza: 'Elf',
    subespecie: 'High',
    clase: 'Warlock | Sorcerer',
    faccion: 'Bastión de las Máscaras',
    estado: 'Dead',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/redmor.webp',
  },
  {
    id: 'navnlos',
    jugador: 'Paula',
    personaje: 'Navnlos',
    raza: 'Elf',
    subespecie: 'High',
    clase: 'Sorcerer | Warlock',
    faccion: 'Pacto de los Fragmentados',
    estado: 'Dead',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/navnlos.webp',
  },
  {
    id: 'bryn',
    jugador: 'Paula',
    personaje: 'Bryn',
    raza: 'Elf',
    subespecie: 'High',
    clase: 'Warlock | Sorcerer',
    faccion: 'Bastión de las Máscaras',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Bryn.webp',
  },

  // ── Eevona ──
  {
    id: 'eevona',
    jugador: 'Eevona',
    personaje: 'Eevona',
    raza: 'Centauro',
    subespecie: 'Semi—Diosa',
    clase: 'Clerigo | Mago',
    faccion: 'Ninguno',
    estado: 'Traitor',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Eevona.webp',
  },

  // ── Curko ──
  {
    id: 'zylevni-byrdumbra',
    jugador: 'Curko',
    personaje: 'Zylevni Byrdumbra',
    raza: 'Human',
    subespecie: 'Calventis',
    clase: 'Hexblade Warlock | Rogue',
    faccion: 'Bastión de las Máscaras',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Zylevni_Byrdumbra.webp',
  },
  {
    id: 'gwynulv-nathair',
    jugador: 'Curko',
    personaje: 'Gwynulv Nathair',
    raza: 'Elf',
    subespecie: 'Tauredhel',
    clase: 'Cosmic Warlock',
    faccion: 'Cámara del Eco',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Gwynulv.webp',
  },
  {
    id: 'ho-lang-rua',
    jugador: 'Curko',
    personaje: 'Ho Lang-Rua',
    raza: 'Tortle',
    subespecie: 'Galápagos Giant Tortoise',
    clase: 'Way of Mercy Monk',
    faccion: 'Rangers Caelestis',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Ho Lang-Rua.webp',
  },

  // ── Lucciano ──
  {
    id: 'edrik',
    jugador: 'Lucciano',
    personaje: 'Edrik',
    raza: 'Human',
    subespecie: 'Hijo de Munimen',
    clase: 'Paladin of Munimen',
    faccion: 'Ninguno',
    estado: 'Missing',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Edrik.webp',
  },

  // ── Cata Caro ──
  {
    id: 'uktspangyu',
    jugador: 'Cata Caro',
    personaje: 'Uktspangyu',
    raza: '',
    subespecie: '',
    clase: 'Ranger',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/uktspangyu2.webp',
  },
  {
    id: 'skaedi',
    jugador: 'Cata Caro',
    personaje: 'Skaedi',
    raza: '',
    subespecie: '',
    clase: 'Bard',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/skaedi_perfil.webp',
  },

  // ── Zampe ──
  {
    id: 'saber',
    jugador: 'Zampe',
    personaje: 'Saber',
    raza: 'Human',
    subespecie: '',
    clase: 'Paladin',
    faccion: 'Rangers Caelestis',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/saber.webp',
  },
  {
    id: 'raider',
    jugador: 'Zampe',
    personaje: 'Raider',
    raza: 'Human',
    subespecie: '',
    clase: 'Fighter',
    faccion: 'Rangers Caelestis',
    estado: 'Dead',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Rider.webp',
  },
  {
    id: 'mago-de-las-flores',
    jugador: 'Zampe',
    personaje: 'mago de las flores',
    raza: 'Human',
    subespecie: '',
    clase: 'BladeSinger Wizard',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/ambrosius.webp',
  },

  // ── Jesus ──
  {
    id: 'cecille',
    jugador: 'Jesus',
    personaje: 'Cecille',
    raza: 'Shifter',
    subespecie: '',
    clase: 'Twilight Cleric',
    faccion: 'Cámara del Eco',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/cecil.webp',
  },
  {
    id: 'kit',
    jugador: 'Jesus',
    personaje: 'Kit',
    raza: 'Dhampir',
    subespecie: '',
    clase: 'Thief Rogue',
    faccion: 'Bastión de las Máscaras',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/kit.webp',
  },
  {
    id: 'inhara',
    jugador: 'Jesus',
    personaje: 'Inhara',
    raza: 'Human',
    subespecie: '',
    clase: 'Chronurgist Wizard',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Inhara.webp',
  },

  // ── Rigo ──
  {
    id: 'vor-tex',
    jugador: 'Rigo',
    personaje: 'Vor-Tex',
    raza: 'Thre-Kreen',
    subespecie: '',
    clase: 'Fighter | Champion',
    faccion: 'Rangers Caelestis',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Vor-Tex.webp',
  },
  {
    id: 'franco-rossi',
    jugador: 'Rigo',
    personaje: 'Franco Rossi',
    raza: 'Human',
    subespecie: '',
    clase: 'Inquisidor | Daemon Hunter',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: [
      'guess_who/thumbs/Franco Rossi.webp',
      'guess_who/thumbs/Inquisidor.webp',
    ],
  },
  {
    id: 'gizmo-heartrings',
    jugador: 'Rigo',
    personaje: 'Gizmo Heartrings',
    raza: 'Lycan',
    subespecie: '',
    clase: 'Merchant | Blacksmith',
    faccion: 'Milites Stellarum',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/gizmo.webp',
  },

  // ── Lucas ──
  {
    id: 'melisent-de-edorel',
    jugador: 'Lucas',
    personaje: 'Melisent Dé Edorel',
    raza: 'Human',
    subespecie: 'Calventina',
    clase: 'Paladin | Fiend Warlock',
    faccion: 'Praesidium Credendi',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: [
      'guess_who/thumbs/Meli.webp',
      'guess_who/thumbs/Evil_Meli.webp',
      'guess_who/thumbs/EvilMeli2_Calventis Arc.webp',
    ],
  },
  {
    id: 'lucca-elster',
    jugador: 'Lucas',
    personaje: 'Lucca Élster',
    raza: 'Human',
    subespecie: 'Aurentina',
    clase: 'Gunslinger | High Roller',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Lucca Élster.webp',
  },
  {
    id: 'juventia-hadriana',
    jugador: 'Lucas',
    personaje: "Juventia M'. Hadriana",
    raza: 'Human',
    subespecie: 'Magnavori',
    clase: 'Pugilist | Sweet Science',
    faccion: 'Lux Memoriae',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Juventia.webp',
  },

  // ── Mauricio ──
  {
    id: 'janis-van-hayleeys',
    jugador: 'Mauricio',
    personaje: 'Janis Van Hayleeys',
    raza: 'Eladrin',
    subespecie: '',
    clase: 'Bard College of Glamour',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: '',
  },
  {
    id: 'maximo-decimo-leonisio',
    jugador: 'Mauricio',
    personaje: 'Maximo Decimo Leonisio',
    raza: 'Leonin',
    subespecie: '',
    clase: 'Pugilist | Squared Circle',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Maximo Decimo Leonisio.webp',
  },
  {
    id: 'benedict-sforza',
    jugador: 'Mauricio',
    personaje: 'Benedict D. Sforza',
    raza: 'Human',
    subespecie: '',
    clase: 'Cleric Eldritch Domain',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: '',
  },

  // ── Ally ──
  {
    id: 'kaya',
    jugador: 'Ally',
    personaje: 'Kaya',
    raza: 'Dragonborn',
    subespecie: '',
    clase: 'Rogue',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Kaya.webp',
  },

  // ── Pelao ──
  {
    id: 'hrungnir',
    jugador: 'Pelao',
    personaje: 'Hrungnir',
    raza: '',
    subespecie: '',
    clase: 'Way of the Open Hand Monk',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Hrungnir.webp',
  },

  // ── Mako ──
  {
    id: 'akllasqa-caisatra',
    jugador: 'Mako',
    personaje: 'Akllasqa Caisatra',
    raza: 'Elf',
    subespecie: 'Certhedel',
    clase: 'Cleric Orden Domain',
    faccion: 'Praesidium Credendi',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Akllasqa_C_hanfu.webp',
  },
  {
    id: 'calus-solarium',
    jugador: 'Mako',
    personaje: 'Calus Solarium',
    raza: 'Human',
    subespecie: 'Magnavori',
    clase: 'Cleric Light Domain',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/callus.webp',
  },

  // ── Nikolai ──
  {
    id: 'laekna',
    jugador: 'Nikolai',
    personaje: 'Lækna',
    raza: 'Construct',
    subespecie: 'A Perfect Human',
    clase: 'Druid | Cleric',
    faccion: 'Cámara del Eco',
    estado: 'Eternally dead',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/laekna_2.webp',
  },
  {
    id: 'allery',
    jugador: 'Nikolai',
    personaje: 'Allery',
    raza: 'Elf',
    subespecie: 'High',
    clase: 'Jeager',
    faccion: 'Bastión de las Máscaras',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Allery.webp',
  },
  {
    id: 'kullervo',
    jugador: 'Nikolai',
    personaje: 'Kullervo',
    raza: 'Reborn',
    subespecie: 'Elf',
    clase: 'Celestial Warlock | Pact of the Blade',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/Kullervo.webp',
  },

  // ── Eric ──

  // ── Paula ── (segundo bloque de la planilla: si es otra jugadora, renombrar acá)
  {
    id: 'soleas-de-astora',
    jugador: 'Paula',
    personaje: 'Soleas de Astora',
    raza: '',
    subespecie: '',
    clase: 'Ranger | Fey Wanderer',
    faccion: 'Bastión de las Máscaras',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: [
      'guess_who/thumbs/soleas terminado.webp',
      'guess_who/thumbs/Soleas de Astora png.webp',
    ],
  },
  {
    id: 'paco-khairtai',
    jugador: 'Paula',
    personaje: 'Paco Khairtai',
    raza: '',
    subespecie: '',
    clase: 'Bard of Spirits',
    faccion: 'Ninguno',
    estado: '',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/paquito.webp',
  },

  // ── Sin jugador en la planilla ──
  // Kropp no estaba en el CSV: sale de guess_who/kropp.png. Faltan sus datos.
  {
    id: 'kropp',
    jugador: '',
    personaje: 'Kropp',
    raza: '',
    subespecie: '',
    clase: '',
    faccion: '',
    estado: 'Dead',
    descripcion: '',
    lore: '',
    imagen: 'guess_who/thumbs/kropp.webp',
  },

];
